### ISSUE TITLE
Thread 1 "gcclassic" received signal SIGSEGV, Segmentation fault.

### ISSUE THREAD

**Issue by crystal00028** [GEOS-ESM/GEOSgcm#851]
There was a segmentation fault when running the model.
Thread 1 "gcclassic" received signal SIGSEGV, Segmentation fault.
0x0000000000981cc4 in cldj_fjx_sub_mod::opmie (dtaux=..., pomegax=..., u0=0.15301745264011474, rfl=..., amf=..., amg=..., jxtra=..., fjact=..., fjtop=...,
    fjbot=..., fibot=..., fsbot=..., fjflx=..., flxd=..., flxd0=..., ldokr=..., lu=72, rc=0, ldokr=...)
    at /home/cry/ExtData/gc_4x5_merra2_fullchem/CodeDir/src/Cloud-J/src/Core/cldj_fjx_sub_mod.F90:796
796           subroutine OPMIE (DTAUX,POMEGAX,U0,RFL,AMF,AMG,JXTRA, &
(gdb) backtrace
#0  0x0000000000981cc4 in cldj_fjx_sub_mod::opmie (dtaux=..., pomegax=..., u0=0.15301745264011474, rfl=..., amf=..., amg=..., jxtra=..., fjact=...,
    fjtop=..., fjbot=..., fibot=..., fsbot=..., fjflx=..., flxd=..., flxd0=..., ldokr=..., lu=72, rc=0, ldokr=...)
    at /home/cry/ExtData/gc_4x5_merra2_fullchem/CodeDir/src/Cloud-J/src/Core/cldj_fjx_sub_mod.F90:796
#1  0x000000000099179c in cldj_fjx_sub_mod::photo_jx (u0=0.15301745264011474, sza=81.198166933588382, rfl=..., solf=0.96650251637029394, lprtj=.FALSE.,
    ppp=..., zzz=..., ttt=..., hhh=..., ddd=..., rrr=..., ooo=..., ccc=..., lwp=..., iwp=..., reffl=..., reffi=..., aersp=..., ndxaer=..., l1u=73, anu=37,
    njxu=200, valjxx=..., skperd=..., swmsq=..., od18=..., ldark=.FALSE., rc=0)
    at /home/cry/ExtData/gc_4x5_merra2_fullchem/CodeDir/src/Cloud-J/src/Core/cldj_fjx_sub_mod.F90:521
#2  0x0000000000971498 in cldj_sub_mod::cloud_jx (u0=0.15301745264011474, sza=81.198166933588382, rfl=..., solf=0.96650251637029394, lprtj=<optimized out>,
    ppp=..., zzz=..., ttt=..., hhh=..., ddd=..., rrr=..., ooo=..., ccc=..., lwp=..., iwp=..., reffl=..., reffi=..., cldf=..., cldcor=0.33000001311302185,
    cldiw=..., aersp=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>,
    ndxaer=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, l1u=73, anu=37, njxu=200, valjxx=..., skperd=...,
    swmsq=..., od18=..., iran=1, nica=0, jcount=0, ldark=.FALSE., wtqca=..., rc=0)
    at /home/cry/ExtData/gc_4x5_merra2_fullchem/CodeDir/src/Cloud-J/src/Core/cldj_sub_mod.F90:225
#3  0x0000000000692aff in cldj_interface_mod::__cldj_interface_mod_MOD_run_cloudj._omp_fn.0 ()
    at /home/cry/ExtData/gc_4x5_merra2_fullchem/CodeDir/src/GEOS-Chem/GeosCore/cldj_interface_mod.F90:948
#4  0x00007ffff7900296 in GOMP_parallel (fn=0x68f440 <cldj_interface_mod::__cldj_interface_mod_MOD_run_cloudj._omp_fn.0>, data=0x7ffffffd2ec0,
    num_threads=6, flags=0) at /tmp/cry/spack-stage/spack-stage-gcc-11.2.0-v6a3cr4sb4izbjcm7z7jhjbetthazs3v/spack-src/libgomp/parallel.c:178
#5  0x000000000069821d in cldj_interface_mod::run_cloudj (input_opt=..., state_chm=..., state_diag=..., state_grid=..., state_met=..., rc=0)
    at /home/cry/ExtData/gc_4x5_merra2_fullchem/CodeDir/src/GEOS-Chem/GeosCore/cldj_interface_mod.F90:435
#6  0x0000000000515723 in photolysis_mod::do_photolysis (input_opt=..., state_chm=..., state_diag=..., state_grid=..., state_met=..., rc=0)
    at /home/cry/ExtData/gc_4x5_merra2_fullchem/CodeDir/src/GEOS-Chem/GeosCore/photolysis_mod.F90:579
#7  0x0000000000463fc0 in fullchem_mod::do_fullchem (input_opt=..., state_chm=..., state_diag=..., state_grid=..., state_met=..., rc=0)
    at /home/cry/ExtData/gc_4x5_merra2_fullchem/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:395
#8  0x000000000041d3b9 in chemistry_mod::do_chemistry (input_opt=..., state_chm=..., state_diag=..., state_grid=..., state_met=..., rc=0)
    at /home/cry/ExtData/gc_4x5_merra2_fullchem/CodeDir/src/GEOS-Chem/GeosCore/chemistry_mod.F90:434
#9  0x0000000000407f16 in geos_chem () at /home/cry/ExtData/gc_4x5_merra2_fullchem/CodeDir/src/GEOS-Chem/Interfaces/GCClassic/main.F90:1456
#10 0x00000000004064b7 in main (argc=<optimized out>, argv=<optimized out>)
    at /home/cry/ExtData/gc_4x5_merra2_fullchem/CodeDir/src/GEOS-Chem/Interfaces/GCClassic/main.F90:32
#11 0x00007ffff7693083 in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#12 0x00000000004064ee in _start () at /home/cry/ExtData/gc_4x5_merra2_fullchem/CodeDir/src/GEOS-Chem/Interfaces/GCClassic/main.F90:32

**Comment by mathomp4** [comment]
@crystal00028 Your traceback seems to be maybe from [GEOS-Chem classic](https://geos-chem.readthedocs.io/en/stable/)?
